//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GodotProj.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Righthand.GodotTscnParser.Engine.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGodotProjListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GodotProjBaseListener : IGodotProjListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] GodotProjParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] GodotProjParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSection([NotNull] GodotProjParser.SectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSection([NotNull] GodotProjParser.SectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.sectionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSectionName([NotNull] GodotProjParser.SectionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.sectionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSectionName([NotNull] GodotProjParser.SectionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.sectionLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSectionLine([NotNull] GodotProjParser.SectionLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.sectionLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSectionLine([NotNull] GodotProjParser.SectionLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] GodotProjParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] GodotProjParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.objectProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectProperty([NotNull] GodotProjParser.ObjectPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.objectProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectProperty([NotNull] GodotProjParser.ObjectPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] GodotProjParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] GodotProjParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyValue([NotNull] GodotProjParser.PropertyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyValue([NotNull] GodotProjParser.PropertyValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyValueArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyValueArray([NotNull] GodotProjParser.PropertyValueArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyValueArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyValueArray([NotNull] GodotProjParser.PropertyValueArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyObjectArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyObjectArray([NotNull] GodotProjParser.PropertyObjectArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyObjectArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyObjectArray([NotNull] GodotProjParser.PropertyObjectArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyObject([NotNull] GodotProjParser.PropertyObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyObject([NotNull] GodotProjParser.PropertyObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.simpleObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleObject([NotNull] GodotProjParser.SimpleObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.simpleObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleObject([NotNull] GodotProjParser.SimpleObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyObjectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyObjectName([NotNull] GodotProjParser.PropertyObjectNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyObjectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyObjectName([NotNull] GodotProjParser.PropertyObjectNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyObjectTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyObjectTypeName([NotNull] GodotProjParser.PropertyObjectTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyObjectTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyObjectTypeName([NotNull] GodotProjParser.PropertyObjectTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] GodotProjParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] GodotProjParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.numericStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericStructure([NotNull] GodotProjParser.NumericStructureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.numericStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericStructure([NotNull] GodotProjParser.NumericStructureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.complexValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexValue([NotNull] GodotProjParser.ComplexValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.complexValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexValue([NotNull] GodotProjParser.ComplexValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] GodotProjParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] GodotProjParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.pairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPairName([NotNull] GodotProjParser.PairNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.pairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPairName([NotNull] GodotProjParser.PairNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.complexPairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexPairName([NotNull] GodotProjParser.ComplexPairNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.complexPairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexPairName([NotNull] GodotProjParser.ComplexPairNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.complexPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexPair([NotNull] GodotProjParser.ComplexPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.complexPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexPair([NotNull] GodotProjParser.ComplexPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] GodotProjParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] GodotProjParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GodotProjParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] GodotProjParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GodotProjParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] GodotProjParser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Righthand.GodotTscnParser.Engine.Grammar
