//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Tscn.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Righthand.GodotTscnParser.Engine.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class TscnParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, KEY=20, NUMBER=21, COMMA=22, START_BRACKET=23, END_BRACKET=24, 
		STRING=25, WS=26;
	public const int
		RULE_file = 0, RULE_fileDescriptor = 1, RULE_extResource = 2, RULE_subResource = 3, 
		RULE_node = 4, RULE_connection = 5, RULE_editable = 6, RULE_object = 7, 
		RULE_property = 8, RULE_propertyName = 9, RULE_extResourceRef = 10, RULE_subResourceRef = 11, 
		RULE_nodePath = 12, RULE_ref = 13, RULE_resourceRef = 14, RULE_complexValue = 15, 
		RULE_objectArray = 16, RULE_complexValueArray = 17, RULE_pair = 18, RULE_pairName = 19, 
		RULE_complexPairName = 20, RULE_complexPair = 21, RULE_predicate = 22, 
		RULE_value = 23, RULE_number = 24;
	public static readonly string[] ruleNames = {
		"file", "fileDescriptor", "extResource", "subResource", "node", "connection", 
		"editable", "object", "property", "propertyName", "extResourceRef", "subResourceRef", 
		"nodePath", "ref", "resourceRef", "complexValue", "objectArray", "complexValueArray", 
		"pair", "pairName", "complexPairName", "complexPair", "predicate", "value", 
		"number"
	};

	private static readonly string[] _LiteralNames = {
		null, "'gd_scene'", "'ext_resource'", "'sub_resource'", "'node'", "'connection'", 
		"'editable'", "'{'", "'}'", "':'", "'ExtResource'", "'('", "')'", "'SubResource'", 
		"'NodePath'", "'&'", "'='", "'true'", "'false'", "'null'", null, null, 
		"','", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "KEY", "NUMBER", "COMMA", 
		"START_BRACKET", "END_BRACKET", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Tscn.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static TscnParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public TscnParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public TscnParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FileDescriptorContext fileDescriptor() {
			return GetRuleContext<FileDescriptorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExtResourceContext[] extResource() {
			return GetRuleContexts<ExtResourceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExtResourceContext extResource(int i) {
			return GetRuleContext<ExtResourceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubResourceContext[] subResource() {
			return GetRuleContexts<SubResourceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubResourceContext subResource(int i) {
			return GetRuleContext<SubResourceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NodeContext[] node() {
			return GetRuleContexts<NodeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NodeContext node(int i) {
			return GetRuleContext<NodeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConnectionContext[] connection() {
			return GetRuleContexts<ConnectionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConnectionContext connection(int i) {
			return GetRuleContext<ConnectionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EditableContext[] editable() {
			return GetRuleContexts<EditableContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EditableContext editable(int i) {
			return GetRuleContext<EditableContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterFile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitFile(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			fileDescriptor();
			State = 54;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 51;
					extResource();
					}
					} 
				}
				State = 56;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 60;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 57;
					subResource();
					}
					} 
				}
				State = 62;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 66;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 63;
					node();
					}
					} 
				}
				State = 68;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			State = 72;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 69;
					connection();
					}
					} 
				}
				State = 74;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==START_BRACKET) {
				{
				{
				State = 75;
				editable();
				}
				}
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileDescriptorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public FileDescriptorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileDescriptor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterFileDescriptor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitFileDescriptor(this);
		}
	}

	[RuleVersion(0)]
	public FileDescriptorContext fileDescriptor() {
		FileDescriptorContext _localctx = new FileDescriptorContext(Context, State);
		EnterRule(_localctx, 2, RULE_fileDescriptor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			Match(START_BRACKET);
			State = 82;
			Match(T__0);
			State = 84;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 83;
				pair();
				}
				}
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 88;
			Match(END_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtResourceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ExtResourceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extResource; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterExtResource(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitExtResource(this);
		}
	}

	[RuleVersion(0)]
	public ExtResourceContext extResource() {
		ExtResourceContext _localctx = new ExtResourceContext(Context, State);
		EnterRule(_localctx, 4, RULE_extResource);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			Match(START_BRACKET);
			State = 91;
			Match(T__1);
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 92;
				pair();
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 97;
			Match(END_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubResourceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexPairContext[] complexPair() {
			return GetRuleContexts<ComplexPairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexPairContext complexPair(int i) {
			return GetRuleContext<ComplexPairContext>(i);
		}
		public SubResourceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subResource; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterSubResource(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitSubResource(this);
		}
	}

	[RuleVersion(0)]
	public SubResourceContext subResource() {
		SubResourceContext _localctx = new SubResourceContext(Context, State);
		EnterRule(_localctx, 6, RULE_subResource);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			Match(START_BRACKET);
			State = 100;
			Match(T__2);
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 101;
				pair();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 106;
			Match(END_BRACKET);
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==KEY) {
				{
				{
				State = 107;
				complexPair();
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NodeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ComplexPairContext[] complexPair() {
			return GetRuleContexts<ComplexPairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexPairContext complexPair(int i) {
			return GetRuleContext<ComplexPairContext>(i);
		}
		public NodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_node; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterNode(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitNode(this);
		}
	}

	[RuleVersion(0)]
	public NodeContext node() {
		NodeContext _localctx = new NodeContext(Context, State);
		EnterRule(_localctx, 8, RULE_node);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			Match(START_BRACKET);
			State = 114;
			Match(T__3);
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 115;
				complexPair();
				}
				}
				State = 118;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 120;
			Match(END_BRACKET);
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==KEY) {
				{
				{
				State = 121;
				complexPair();
				}
				}
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConnectionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ConnectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_connection; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterConnection(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitConnection(this);
		}
	}

	[RuleVersion(0)]
	public ConnectionContext connection() {
		ConnectionContext _localctx = new ConnectionContext(Context, State);
		EnterRule(_localctx, 10, RULE_connection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			Match(START_BRACKET);
			State = 128;
			Match(T__4);
			State = 130;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 129;
				pair();
				}
				}
				State = 132;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 134;
			Match(END_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EditableContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public EditableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_editable; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterEditable(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitEditable(this);
		}
	}

	[RuleVersion(0)]
	public EditableContext editable() {
		EditableContext _localctx = new EditableContext(Context, State);
		EnterRule(_localctx, 12, RULE_editable);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136;
			Match(START_BRACKET);
			State = 137;
			Match(T__5);
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 138;
				pair();
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY );
			State = 143;
			Match(END_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PropertyContext[] property() {
			return GetRuleContexts<PropertyContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PropertyContext property(int i) {
			return GetRuleContext<PropertyContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(TscnParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(TscnParser.COMMA, i);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 14, RULE_object);
		int _la;
		try {
			State = 158;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145;
				Match(T__6);
				State = 146;
				property();
				State = 151;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 147;
					Match(COMMA);
					State = 148;
					property();
					}
					}
					State = 153;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 154;
				Match(T__7);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 156;
				Match(T__6);
				State = 157;
				Match(T__7);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext complexValue() {
			return GetRuleContext<ComplexValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RefContext @ref() {
			return GetRuleContext<RefContext>(0);
		}
		public PropertyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_property; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterProperty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitProperty(this);
		}
	}

	[RuleVersion(0)]
	public PropertyContext property() {
		PropertyContext _localctx = new PropertyContext(Context, State);
		EnterRule(_localctx, 16, RULE_property);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				{
				State = 160;
				propertyName();
				}
				break;
			case T__14:
				{
				State = 161;
				@ref();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 164;
			Match(T__8);
			State = 165;
			complexValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(TscnParser.STRING, 0); }
		public PropertyNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterPropertyName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitPropertyName(this);
		}
	}

	[RuleVersion(0)]
	public PropertyNameContext propertyName() {
		PropertyNameContext _localctx = new PropertyNameContext(Context, State);
		EnterRule(_localctx, 18, RULE_propertyName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtResourceRefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ResourceRefContext resourceRef() {
			return GetRuleContext<ResourceRefContext>(0);
		}
		public ExtResourceRefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extResourceRef; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterExtResourceRef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitExtResourceRef(this);
		}
	}

	[RuleVersion(0)]
	public ExtResourceRefContext extResourceRef() {
		ExtResourceRefContext _localctx = new ExtResourceRefContext(Context, State);
		EnterRule(_localctx, 20, RULE_extResourceRef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			Match(T__9);
			State = 170;
			Match(T__10);
			State = 171;
			resourceRef();
			State = 172;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubResourceRefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ResourceRefContext resourceRef() {
			return GetRuleContext<ResourceRefContext>(0);
		}
		public SubResourceRefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subResourceRef; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterSubResourceRef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitSubResourceRef(this);
		}
	}

	[RuleVersion(0)]
	public SubResourceRefContext subResourceRef() {
		SubResourceRefContext _localctx = new SubResourceRefContext(Context, State);
		EnterRule(_localctx, 22, RULE_subResourceRef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174;
			Match(T__12);
			State = 175;
			Match(T__10);
			State = 176;
			resourceRef();
			State = 177;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NodePathContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ResourceRefContext resourceRef() {
			return GetRuleContext<ResourceRefContext>(0);
		}
		public NodePathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nodePath; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterNodePath(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitNodePath(this);
		}
	}

	[RuleVersion(0)]
	public NodePathContext nodePath() {
		NodePathContext _localctx = new NodePathContext(Context, State);
		EnterRule(_localctx, 24, RULE_nodePath);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			Match(T__13);
			State = 180;
			Match(T__10);
			State = 181;
			resourceRef();
			State = 182;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		public RefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterRef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitRef(this);
		}
	}

	[RuleVersion(0)]
	public RefContext @ref() {
		RefContext _localctx = new RefContext(Context, State);
		EnterRule(_localctx, 26, RULE_ref);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(T__14);
			State = 185;
			propertyName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResourceRefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(TscnParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(TscnParser.NUMBER, 0); }
		public ResourceRefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resourceRef; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterResourceRef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitResourceRef(this);
		}
	}

	[RuleVersion(0)]
	public ResourceRefContext resourceRef() {
		ResourceRefContext _localctx = new ResourceRefContext(Context, State);
		EnterRule(_localctx, 28, RULE_resourceRef);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			_la = TokenStream.LA(1);
			if ( !(_la==NUMBER || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ObjectArrayContext objectArray() {
			return GetRuleContext<ObjectArrayContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueArrayContext complexValueArray() {
			return GetRuleContext<ComplexValueArrayContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExtResourceRefContext extResourceRef() {
			return GetRuleContext<ExtResourceRefContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubResourceRefContext subResourceRef() {
			return GetRuleContext<SubResourceRefContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NodePathContext nodePath() {
			return GetRuleContext<NodePathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PredicateContext predicate() {
			return GetRuleContext<PredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ComplexValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterComplexValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitComplexValue(this);
		}
	}

	[RuleVersion(0)]
	public ComplexValueContext complexValue() {
		ComplexValueContext _localctx = new ComplexValueContext(Context, State);
		EnterRule(_localctx, 30, RULE_complexValue);
		try {
			State = 197;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 189;
				objectArray();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 190;
				@object();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 191;
				complexValueArray();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 192;
				extResourceRef();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 193;
				subResourceRef();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 194;
				nodePath();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 195;
				predicate();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 196;
				value();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext[] @object() {
			return GetRuleContexts<ObjectContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object(int i) {
			return GetRuleContext<ObjectContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(TscnParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(TscnParser.COMMA, i);
		}
		public ObjectArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectArray; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterObjectArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitObjectArray(this);
		}
	}

	[RuleVersion(0)]
	public ObjectArrayContext objectArray() {
		ObjectArrayContext _localctx = new ObjectArrayContext(Context, State);
		EnterRule(_localctx, 32, RULE_objectArray);
		int _la;
		try {
			State = 212;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 199;
				Match(START_BRACKET);
				State = 200;
				@object();
				State = 205;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 201;
					Match(COMMA);
					State = 202;
					@object();
					}
					}
					State = 207;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 208;
				Match(END_BRACKET);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 210;
				Match(START_BRACKET);
				State = 211;
				Match(END_BRACKET);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexValueArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode START_BRACKET() { return GetToken(TscnParser.START_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext[] complexValue() {
			return GetRuleContexts<ComplexValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext complexValue(int i) {
			return GetRuleContext<ComplexValueContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END_BRACKET() { return GetToken(TscnParser.END_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(TscnParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(TscnParser.COMMA, i);
		}
		public ComplexValueArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexValueArray; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterComplexValueArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitComplexValueArray(this);
		}
	}

	[RuleVersion(0)]
	public ComplexValueArrayContext complexValueArray() {
		ComplexValueArrayContext _localctx = new ComplexValueArrayContext(Context, State);
		EnterRule(_localctx, 34, RULE_complexValueArray);
		int _la;
		try {
			State = 227;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 214;
				Match(START_BRACKET);
				State = 215;
				complexValue();
				State = 220;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 216;
					Match(COMMA);
					State = 217;
					complexValue();
					}
					}
					State = 222;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 223;
				Match(END_BRACKET);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 225;
				Match(START_BRACKET);
				State = 226;
				Match(END_BRACKET);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PairNameContext pairName() {
			return GetRuleContext<PairNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext complexValue() {
			return GetRuleContext<ComplexValueContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 36, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 229;
			pairName();
			State = 230;
			Match(T__15);
			State = 231;
			complexValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(TscnParser.KEY, 0); }
		public PairNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pairName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterPairName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitPairName(this);
		}
	}

	[RuleVersion(0)]
	public PairNameContext pairName() {
		PairNameContext _localctx = new PairNameContext(Context, State);
		EnterRule(_localctx, 38, RULE_pairName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			Match(KEY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexPairNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(TscnParser.KEY, 0); }
		public ComplexPairNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexPairName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterComplexPairName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitComplexPairName(this);
		}
	}

	[RuleVersion(0)]
	public ComplexPairNameContext complexPairName() {
		ComplexPairNameContext _localctx = new ComplexPairNameContext(Context, State);
		EnterRule(_localctx, 40, RULE_complexPairName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 235;
			Match(KEY);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexPairContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ComplexPairNameContext complexPairName() {
			return GetRuleContext<ComplexPairNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext complexValue() {
			return GetRuleContext<ComplexValueContext>(0);
		}
		public ComplexPairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexPair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterComplexPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitComplexPair(this);
		}
	}

	[RuleVersion(0)]
	public ComplexPairContext complexPair() {
		ComplexPairContext _localctx = new ComplexPairContext(Context, State);
		EnterRule(_localctx, 42, RULE_complexPair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 237;
			complexPairName();
			State = 238;
			Match(T__15);
			State = 239;
			complexValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(TscnParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext[] complexValue() {
			return GetRuleContexts<ComplexValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComplexValueContext complexValue(int i) {
			return GetRuleContext<ComplexValueContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(TscnParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(TscnParser.COMMA, i);
		}
		public PredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterPredicate(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitPredicate(this);
		}
	}

	[RuleVersion(0)]
	public PredicateContext predicate() {
		PredicateContext _localctx = new PredicateContext(Context, State);
		EnterRule(_localctx, 44, RULE_predicate);
		int _la;
		try {
			State = 256;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 241;
				Match(KEY);
				State = 242;
				Match(T__10);
				State = 243;
				complexValue();
				State = 248;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 244;
					Match(COMMA);
					State = 245;
					complexValue();
					}
					}
					State = 250;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 251;
				Match(T__11);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 253;
				Match(KEY);
				State = 254;
				Match(T__10);
				State = 255;
				Match(T__11);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(TscnParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(TscnParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RefContext @ref() {
			return GetRuleContext<RefContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 46, RULE_value);
		try {
			State = 264;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 258;
				Match(NUMBER);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 2);
				{
				State = 259;
				Match(STRING);
				}
				break;
			case T__14:
				EnterOuterAlt(_localctx, 3);
				{
				State = 260;
				@ref();
				}
				break;
			case T__16:
				EnterOuterAlt(_localctx, 4);
				{
				State = 261;
				Match(T__16);
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 5);
				{
				State = 262;
				Match(T__17);
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 6);
				{
				State = 263;
				Match(T__18);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(TscnParser.NUMBER, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITscnListener typedListener = listener as ITscnListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 48, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 266;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,26,269,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,5,0,53,8,0,10,0,12,0,56,9,0,1,0,
		5,0,59,8,0,10,0,12,0,62,9,0,1,0,5,0,65,8,0,10,0,12,0,68,9,0,1,0,5,0,71,
		8,0,10,0,12,0,74,9,0,1,0,5,0,77,8,0,10,0,12,0,80,9,0,1,1,1,1,1,1,4,1,85,
		8,1,11,1,12,1,86,1,1,1,1,1,2,1,2,1,2,4,2,94,8,2,11,2,12,2,95,1,2,1,2,1,
		3,1,3,1,3,4,3,103,8,3,11,3,12,3,104,1,3,1,3,5,3,109,8,3,10,3,12,3,112,
		9,3,1,4,1,4,1,4,4,4,117,8,4,11,4,12,4,118,1,4,1,4,5,4,123,8,4,10,4,12,
		4,126,9,4,1,5,1,5,1,5,4,5,131,8,5,11,5,12,5,132,1,5,1,5,1,6,1,6,1,6,4,
		6,140,8,6,11,6,12,6,141,1,6,1,6,1,7,1,7,1,7,1,7,5,7,150,8,7,10,7,12,7,
		153,9,7,1,7,1,7,1,7,1,7,3,7,159,8,7,1,8,1,8,3,8,163,8,8,1,8,1,8,1,8,1,
		9,1,9,1,10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,
		1,12,1,12,1,13,1,13,1,13,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,
		1,15,3,15,198,8,15,1,16,1,16,1,16,1,16,5,16,204,8,16,10,16,12,16,207,9,
		16,1,16,1,16,1,16,1,16,3,16,213,8,16,1,17,1,17,1,17,1,17,5,17,219,8,17,
		10,17,12,17,222,9,17,1,17,1,17,1,17,1,17,3,17,228,8,17,1,18,1,18,1,18,
		1,18,1,19,1,19,1,20,1,20,1,21,1,21,1,21,1,21,1,22,1,22,1,22,1,22,1,22,
		5,22,247,8,22,10,22,12,22,250,9,22,1,22,1,22,1,22,1,22,1,22,3,22,257,8,
		22,1,23,1,23,1,23,1,23,1,23,1,23,3,23,265,8,23,1,24,1,24,1,24,0,0,25,0,
		2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,0,
		1,2,0,21,21,25,25,277,0,50,1,0,0,0,2,81,1,0,0,0,4,90,1,0,0,0,6,99,1,0,
		0,0,8,113,1,0,0,0,10,127,1,0,0,0,12,136,1,0,0,0,14,158,1,0,0,0,16,162,
		1,0,0,0,18,167,1,0,0,0,20,169,1,0,0,0,22,174,1,0,0,0,24,179,1,0,0,0,26,
		184,1,0,0,0,28,187,1,0,0,0,30,197,1,0,0,0,32,212,1,0,0,0,34,227,1,0,0,
		0,36,229,1,0,0,0,38,233,1,0,0,0,40,235,1,0,0,0,42,237,1,0,0,0,44,256,1,
		0,0,0,46,264,1,0,0,0,48,266,1,0,0,0,50,54,3,2,1,0,51,53,3,4,2,0,52,51,
		1,0,0,0,53,56,1,0,0,0,54,52,1,0,0,0,54,55,1,0,0,0,55,60,1,0,0,0,56,54,
		1,0,0,0,57,59,3,6,3,0,58,57,1,0,0,0,59,62,1,0,0,0,60,58,1,0,0,0,60,61,
		1,0,0,0,61,66,1,0,0,0,62,60,1,0,0,0,63,65,3,8,4,0,64,63,1,0,0,0,65,68,
		1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,0,67,72,1,0,0,0,68,66,1,0,0,0,69,71,
		3,10,5,0,70,69,1,0,0,0,71,74,1,0,0,0,72,70,1,0,0,0,72,73,1,0,0,0,73,78,
		1,0,0,0,74,72,1,0,0,0,75,77,3,12,6,0,76,75,1,0,0,0,77,80,1,0,0,0,78,76,
		1,0,0,0,78,79,1,0,0,0,79,1,1,0,0,0,80,78,1,0,0,0,81,82,5,23,0,0,82,84,
		5,1,0,0,83,85,3,36,18,0,84,83,1,0,0,0,85,86,1,0,0,0,86,84,1,0,0,0,86,87,
		1,0,0,0,87,88,1,0,0,0,88,89,5,24,0,0,89,3,1,0,0,0,90,91,5,23,0,0,91,93,
		5,2,0,0,92,94,3,36,18,0,93,92,1,0,0,0,94,95,1,0,0,0,95,93,1,0,0,0,95,96,
		1,0,0,0,96,97,1,0,0,0,97,98,5,24,0,0,98,5,1,0,0,0,99,100,5,23,0,0,100,
		102,5,3,0,0,101,103,3,36,18,0,102,101,1,0,0,0,103,104,1,0,0,0,104,102,
		1,0,0,0,104,105,1,0,0,0,105,106,1,0,0,0,106,110,5,24,0,0,107,109,3,42,
		21,0,108,107,1,0,0,0,109,112,1,0,0,0,110,108,1,0,0,0,110,111,1,0,0,0,111,
		7,1,0,0,0,112,110,1,0,0,0,113,114,5,23,0,0,114,116,5,4,0,0,115,117,3,42,
		21,0,116,115,1,0,0,0,117,118,1,0,0,0,118,116,1,0,0,0,118,119,1,0,0,0,119,
		120,1,0,0,0,120,124,5,24,0,0,121,123,3,42,21,0,122,121,1,0,0,0,123,126,
		1,0,0,0,124,122,1,0,0,0,124,125,1,0,0,0,125,9,1,0,0,0,126,124,1,0,0,0,
		127,128,5,23,0,0,128,130,5,5,0,0,129,131,3,36,18,0,130,129,1,0,0,0,131,
		132,1,0,0,0,132,130,1,0,0,0,132,133,1,0,0,0,133,134,1,0,0,0,134,135,5,
		24,0,0,135,11,1,0,0,0,136,137,5,23,0,0,137,139,5,6,0,0,138,140,3,36,18,
		0,139,138,1,0,0,0,140,141,1,0,0,0,141,139,1,0,0,0,141,142,1,0,0,0,142,
		143,1,0,0,0,143,144,5,24,0,0,144,13,1,0,0,0,145,146,5,7,0,0,146,151,3,
		16,8,0,147,148,5,22,0,0,148,150,3,16,8,0,149,147,1,0,0,0,150,153,1,0,0,
		0,151,149,1,0,0,0,151,152,1,0,0,0,152,154,1,0,0,0,153,151,1,0,0,0,154,
		155,5,8,0,0,155,159,1,0,0,0,156,157,5,7,0,0,157,159,5,8,0,0,158,145,1,
		0,0,0,158,156,1,0,0,0,159,15,1,0,0,0,160,163,3,18,9,0,161,163,3,26,13,
		0,162,160,1,0,0,0,162,161,1,0,0,0,163,164,1,0,0,0,164,165,5,9,0,0,165,
		166,3,30,15,0,166,17,1,0,0,0,167,168,5,25,0,0,168,19,1,0,0,0,169,170,5,
		10,0,0,170,171,5,11,0,0,171,172,3,28,14,0,172,173,5,12,0,0,173,21,1,0,
		0,0,174,175,5,13,0,0,175,176,5,11,0,0,176,177,3,28,14,0,177,178,5,12,0,
		0,178,23,1,0,0,0,179,180,5,14,0,0,180,181,5,11,0,0,181,182,3,28,14,0,182,
		183,5,12,0,0,183,25,1,0,0,0,184,185,5,15,0,0,185,186,3,18,9,0,186,27,1,
		0,0,0,187,188,7,0,0,0,188,29,1,0,0,0,189,198,3,32,16,0,190,198,3,14,7,
		0,191,198,3,34,17,0,192,198,3,20,10,0,193,198,3,22,11,0,194,198,3,24,12,
		0,195,198,3,44,22,0,196,198,3,46,23,0,197,189,1,0,0,0,197,190,1,0,0,0,
		197,191,1,0,0,0,197,192,1,0,0,0,197,193,1,0,0,0,197,194,1,0,0,0,197,195,
		1,0,0,0,197,196,1,0,0,0,198,31,1,0,0,0,199,200,5,23,0,0,200,205,3,14,7,
		0,201,202,5,22,0,0,202,204,3,14,7,0,203,201,1,0,0,0,204,207,1,0,0,0,205,
		203,1,0,0,0,205,206,1,0,0,0,206,208,1,0,0,0,207,205,1,0,0,0,208,209,5,
		24,0,0,209,213,1,0,0,0,210,211,5,23,0,0,211,213,5,24,0,0,212,199,1,0,0,
		0,212,210,1,0,0,0,213,33,1,0,0,0,214,215,5,23,0,0,215,220,3,30,15,0,216,
		217,5,22,0,0,217,219,3,30,15,0,218,216,1,0,0,0,219,222,1,0,0,0,220,218,
		1,0,0,0,220,221,1,0,0,0,221,223,1,0,0,0,222,220,1,0,0,0,223,224,5,24,0,
		0,224,228,1,0,0,0,225,226,5,23,0,0,226,228,5,24,0,0,227,214,1,0,0,0,227,
		225,1,0,0,0,228,35,1,0,0,0,229,230,3,38,19,0,230,231,5,16,0,0,231,232,
		3,30,15,0,232,37,1,0,0,0,233,234,5,20,0,0,234,39,1,0,0,0,235,236,5,20,
		0,0,236,41,1,0,0,0,237,238,3,40,20,0,238,239,5,16,0,0,239,240,3,30,15,
		0,240,43,1,0,0,0,241,242,5,20,0,0,242,243,5,11,0,0,243,248,3,30,15,0,244,
		245,5,22,0,0,245,247,3,30,15,0,246,244,1,0,0,0,247,250,1,0,0,0,248,246,
		1,0,0,0,248,249,1,0,0,0,249,251,1,0,0,0,250,248,1,0,0,0,251,252,5,12,0,
		0,252,257,1,0,0,0,253,254,5,20,0,0,254,255,5,11,0,0,255,257,5,12,0,0,256,
		241,1,0,0,0,256,253,1,0,0,0,257,45,1,0,0,0,258,265,5,21,0,0,259,265,5,
		25,0,0,260,265,3,26,13,0,261,265,5,17,0,0,262,265,5,18,0,0,263,265,5,19,
		0,0,264,258,1,0,0,0,264,259,1,0,0,0,264,260,1,0,0,0,264,261,1,0,0,0,264,
		262,1,0,0,0,264,263,1,0,0,0,265,47,1,0,0,0,266,267,5,21,0,0,267,49,1,0,
		0,0,24,54,60,66,72,78,86,95,104,110,118,124,132,141,151,158,162,197,205,
		212,220,227,248,256,264
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Righthand.GodotTscnParser.Engine.Grammar
