//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Tscn.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Righthand.GodotTscnParser.Engine.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITscnListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TscnBaseListener : ITscnListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] TscnParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] TscnParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.fileDescriptor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileDescriptor([NotNull] TscnParser.FileDescriptorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.fileDescriptor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileDescriptor([NotNull] TscnParser.FileDescriptorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.extResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtResource([NotNull] TscnParser.ExtResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.extResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtResource([NotNull] TscnParser.ExtResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.subResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubResource([NotNull] TscnParser.SubResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.subResource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubResource([NotNull] TscnParser.SubResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNode([NotNull] TscnParser.NodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNode([NotNull] TscnParser.NodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.connection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnection([NotNull] TscnParser.ConnectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.connection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnection([NotNull] TscnParser.ConnectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.editable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEditable([NotNull] TscnParser.EditableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.editable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEditable([NotNull] TscnParser.EditableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] TscnParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] TscnParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] TscnParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] TscnParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] TscnParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] TscnParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.extResourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtResourceRef([NotNull] TscnParser.ExtResourceRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.extResourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtResourceRef([NotNull] TscnParser.ExtResourceRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.subResourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubResourceRef([NotNull] TscnParser.SubResourceRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.subResourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubResourceRef([NotNull] TscnParser.SubResourceRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.nodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodePath([NotNull] TscnParser.NodePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.nodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodePath([NotNull] TscnParser.NodePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.ref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRef([NotNull] TscnParser.RefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.ref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRef([NotNull] TscnParser.RefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.resourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResourceRef([NotNull] TscnParser.ResourceRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.resourceRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResourceRef([NotNull] TscnParser.ResourceRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexValue([NotNull] TscnParser.ComplexValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexValue([NotNull] TscnParser.ComplexValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.emptyArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyArray([NotNull] TscnParser.EmptyArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.emptyArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyArray([NotNull] TscnParser.EmptyArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexValueArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexValueArray([NotNull] TscnParser.ComplexValueArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexValueArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexValueArray([NotNull] TscnParser.ComplexValueArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] TscnParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] TscnParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.pairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPairName([NotNull] TscnParser.PairNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.pairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPairName([NotNull] TscnParser.PairNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexPairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexPairName([NotNull] TscnParser.ComplexPairNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexPairName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexPairName([NotNull] TscnParser.ComplexPairNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexPair([NotNull] TscnParser.ComplexPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexPair([NotNull] TscnParser.ComplexPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] TscnParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] TscnParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] TscnParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] TscnParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericType([NotNull] TscnParser.GenericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericType([NotNull] TscnParser.GenericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] TscnParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] TscnParser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Righthand.GodotTscnParser.Engine.Grammar
