//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Tscn.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Righthand.GodotTscnParser.Engine.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TscnParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ITscnListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] TscnParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] TscnParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.fileDescriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileDescriptor([NotNull] TscnParser.FileDescriptorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.fileDescriptor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileDescriptor([NotNull] TscnParser.FileDescriptorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.extResource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtResource([NotNull] TscnParser.ExtResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.extResource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtResource([NotNull] TscnParser.ExtResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.subResource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubResource([NotNull] TscnParser.SubResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.subResource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubResource([NotNull] TscnParser.SubResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode([NotNull] TscnParser.NodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode([NotNull] TscnParser.NodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.connection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnection([NotNull] TscnParser.ConnectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.connection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnection([NotNull] TscnParser.ConnectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.editable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEditable([NotNull] TscnParser.EditableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.editable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEditable([NotNull] TscnParser.EditableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] TscnParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] TscnParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty([NotNull] TscnParser.PropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty([NotNull] TscnParser.PropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyName([NotNull] TscnParser.PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyName([NotNull] TscnParser.PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.extResourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtResourceRef([NotNull] TscnParser.ExtResourceRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.extResourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtResourceRef([NotNull] TscnParser.ExtResourceRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.subResourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubResourceRef([NotNull] TscnParser.SubResourceRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.subResourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubResourceRef([NotNull] TscnParser.SubResourceRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.nodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNodePath([NotNull] TscnParser.NodePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.nodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNodePath([NotNull] TscnParser.NodePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRef([NotNull] TscnParser.RefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRef([NotNull] TscnParser.RefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.resourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResourceRef([NotNull] TscnParser.ResourceRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.resourceRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResourceRef([NotNull] TscnParser.ResourceRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.numericStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericStructure([NotNull] TscnParser.NumericStructureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.numericStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericStructure([NotNull] TscnParser.NumericStructureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexValue([NotNull] TscnParser.ComplexValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexValue([NotNull] TscnParser.ComplexValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.objectArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectArray([NotNull] TscnParser.ObjectArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.objectArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectArray([NotNull] TscnParser.ObjectArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexValueArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexValueArray([NotNull] TscnParser.ComplexValueArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexValueArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexValueArray([NotNull] TscnParser.ComplexValueArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] TscnParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] TscnParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.pairName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPairName([NotNull] TscnParser.PairNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.pairName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPairName([NotNull] TscnParser.PairNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexPairName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexPairName([NotNull] TscnParser.ComplexPairNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexPairName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexPairName([NotNull] TscnParser.ComplexPairNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.complexPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexPair([NotNull] TscnParser.ComplexPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.complexPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexPair([NotNull] TscnParser.ComplexPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] TscnParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] TscnParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TscnParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] TscnParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TscnParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] TscnParser.NumberContext context);
}
} // namespace Righthand.GodotTscnParser.Engine.Grammar
